name: Upload Website with terraform

on:
  workflow_dispatch:
    branches:
      - test
  push:
    branches:
      - test
    paths:
      - 'terraform/'
      - 'Resume-website/'
permissions:
  contents: read
  issues: write

env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  backend-aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@master
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init and validate
        working-directory: ./terraform
        run: terraform init
      - name: terraform plan and test
        working-directory: ./terraform
        run: terraform plan -var "aws_bucket_name=${{ secrets.AWS_S3_BUCKET }}"
      - name: approval required
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: shantamsultania
          minimum-approvals: 1
          issue-title: "Deploying v1.0.0 to prod"
          issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to prod."
          exclude-workflow-initiator-as-approver: false
      - name: terraform apply to prod
        working-directory: ./terraform
        run: terraform apply -var "aws_bucket_name=${{ secrets.AWS_S3_BUCKET }}" -no-color -input=false -auto-approve
  front-end-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@master
      - name: upload to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'Resume-website'

